'use strict';

/**
 * Message Model
 *
 * Stores every individual message exchanged in a conversation.
 * Both user messages and AI responses are stored here, distinguished by `role`.
 *
 * Design decisions:
 *   - Separate collection (not embedded in Conversation) because a chat can
 *     have thousands of messages. Embedding would hit MongoDB's 16 MB document
 *     limit and make partial reads impossible.
 *   - telegramMessageId is stored so we can reference/edit Telegram messages
 *     (e.g. for regeneration — we edit the original bot message in-place).
 *   - tokens tracks OpenAI usage per message for cost analytics.
 *   - isHidden allows soft-deleting individual messages without breaking
 *     the sequence index used for context window reconstruction.
 */

const mongoose = require('mongoose');

// ---------------------------------------------------------------------------
// Sub-schema: Token usage (OpenAI cost tracking)
// ---------------------------------------------------------------------------
const tokenUsageSchema = new mongoose.Schema(
  {
    promptTokens: { type: Number, default: 0 },
    completionTokens: { type: Number, default: 0 },
    totalTokens: { type: Number, default: 0 },
  },
  { _id: false }
);

// ---------------------------------------------------------------------------
// Main Schema
// ---------------------------------------------------------------------------
const messageSchema = new mongoose.Schema(
  {
    // ── Relationships ──────────────────────────────────────────────────────
    conversationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Conversation',
      required: true,
      index: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    telegramId: {
      type: Number,
      required: true,
      index: true,
    },

    // ── Message content ────────────────────────────────────────────────────
    // role matches OpenAI's convention: 'user' | 'assistant' | 'system'
    role: {
      type: String,
      enum: ['user', 'assistant', 'system'],
      required: true,
      index: true,
    },
    content: {
      type: String,
      required: true,
      maxlength: 8000,
    },

    // ── Telegram references ────────────────────────────────────────────────
    // The Telegram message ID for the user's message (for context linking)
    telegramMessageId: {
      type: Number,
      default: null,
    },
    // The Telegram message ID of the bot's response (for in-place edits)
    botMessageId: {
      type: Number,
      default: null,
    },

    // ── Media ─────────────────────────────────────────────────────────────
    // If this message includes an image sent by the user (vision feature)
    hasImage: { type: Boolean, default: false },
    imageFileId: { type: String, default: null }, // Telegram file_id
    // If this message triggered an AI image generation
    generatedImageId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'GeneratedImage',
      default: null,
    },

    // ── AI metadata ───────────────────────────────────────────────────────
    personality: { type: String, default: null, maxlength: 32 },
    model: { type: String, default: null, maxlength: 64 }, // e.g. 'gpt-4o'
    tokenUsage: {
      type: tokenUsageSchema,
      default: null,
    },
    // Was this message regenerated by the user?
    isRegenerated: { type: Boolean, default: false },
    regenerationCount: { type: Number, default: 0, min: 0 },

    // ── Sequence ──────────────────────────────────────────────────────────
    // Monotonically increasing index within the conversation.
    // Used to reconstruct the ordered context window without relying on
    // createdAt (which can have millisecond collisions).
    sequenceIndex: {
      type: Number,
      required: true,
      min: 0,
    },

    // ── Moderation ────────────────────────────────────────────────────────
    isHidden: { type: Boolean, default: false, index: true },
    hiddenReason: { type: String, default: null, maxlength: 200 },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ---------------------------------------------------------------------------
// Indexes
// ---------------------------------------------------------------------------

// Primary read pattern: fetch ordered messages for a conversation
messageSchema.index({ conversationId: 1, sequenceIndex: 1 });

// Context window fetch: last N visible messages
messageSchema.index({ conversationId: 1, isHidden: 1, sequenceIndex: -1 });

// Admin / analytics: messages per user over time
messageSchema.index({ userId: 1, createdAt: -1 });

// Token usage analytics
messageSchema.index({ createdAt: -1, role: 1 });

// ---------------------------------------------------------------------------
// Statics
// ---------------------------------------------------------------------------

/**
 * Fetch the last N messages for a conversation in chronological order.
 * Used to build the OpenAI context window.
 * @param {ObjectId} conversationId
 * @param {number} limit  — how many messages to include
 * @param {number} afterIndex — only fetch messages after this sequenceIndex
 *                              (used when a summary exists for earlier messages)
 */
messageSchema.statics.getContextWindow = function (
  conversationId,
  limit = 20,
  afterIndex = 0
) {
  return this.find(
    {
      conversationId,
      isHidden: false,
      sequenceIndex: { $gt: afterIndex },
    },
    { role: 1, content: 1, sequenceIndex: 1, hasImage: 1 }
  )
    .sort({ sequenceIndex: -1 })
    .limit(limit)
    .lean()
    .then((msgs) => msgs.reverse()); // return in chronological order
};

/**
 * Get the next sequence index for a conversation.
 * Atomically safe — uses $max aggregation on existing messages.
 */
messageSchema.statics.nextSequenceIndex = async function (conversationId) {
  const result = await this.findOne(
    { conversationId },
    { sequenceIndex: 1 }
  )
    .sort({ sequenceIndex: -1 })
    .lean();

  return result ? result.sequenceIndex + 1 : 0;
};

module.exports = mongoose.model('Message', messageSchema);
